# Default environment
default:

  # Documented in LogSettings class
  log_level: info
  log_filename_prefix: main

  # Documented in AppSettings class
  app_packages:
    - cl.runtime
    - cl.convince
    - stubs.cl.runtime
    - stubs.cl.convince

  # Documented in DbSettings class
  db_id: temp_convince_main
  db_type: SqliteDb

  # Documented in ApiSettings class
  api_hostname: localhost
  api_port: 7008

  # Documented in PreloadSettings class
  preload_dirs:
    - preloads/cl
    - preloads/stubs

  # Documented in LlmSettings class
  llm_locale: en-US
  llm_full: gpt-4o
  llm_mini: gpt-4o-mini

# Test environment
test:

  # Documented in QaSettings class
  qa_db_types:
    - SqliteDb
    - BasicMongoMockDb

  # Documented in LogSettings class
  log_filename_prefix: tests
