# Default environment
default:

  # Documented in LogSettings class
  log_level: info
  log_filename_prefix: main

  # Documented in EnvSettings class
  env_id: temp_hackathon_main
  env_tenant: temp_tenant
  env_packages:
    - cl.runtime
    - cl.convince
    - cl.hackathon
    - stubs.cl.runtime
    - stubs.cl.convince
    - stubs.cl.hackathon

  # Documented in DbSettings class
  db_id: temp_hackathon_main
  db_type: SqliteDb

  # Documented in CelerySettings class
  celery_broker_uri: mongodb://localhost:27017/celery-{context_id}
  # celery_broker_uri: sqlalchemy+sqlite:///{project_dir}/celery-{context_id}.db

  # Documented in ApiSettings class
  api_hostname: localhost
  api_port: 7008

  # Documented in PreloadSettings class
  preload_dirs:
    - preloads/cl
    - preloads/stubs

  # Documented in LlmSettings class
  llm_type: GptLlm
  llm_id: gpt-4o
  llm_locale: en-US

# Test environment
testing:

  # Documented in QaSettings class
  qa_db_types:
    - SqliteDb
    - BasicMongoMockDb

  # Documented in LogSettings class
  log_filename_prefix: tests
